name: Checkout_Example

on:
  workflow_dispatch:
    
jobs:
  demo_checkout:
     runs-on: ubuntu-latest

     steps:
       - name: List Space
         run: ls-la ${{github.workspace}}

       - name: Checkout source code
         uses: actions/Checkout@v4  #this will go to the github page with the link /actions/checkout

       - name: List space again
         run: ls-la ${{github.workspace}}