name: 02 conditional steps

on:
  workflow_dispatch:

jobs:
  example_job:
     runs-on: ubuntu-latest

     steps:
       - name: Step 1-Exit code 0
         id: successful_step
         run: |
            echo "exit code 0"
            exit 0 #Success (exit_code 0)
         shell: bash

       - name: Step 2- Execute IF Previous Succeded
         if: ${{success()}}
         run: |
             echo "Running because the previous step has Succeded"

       - name: Step 3- I am Failing
         run: |
             echo "I am failing"
             exit 1 # Failure (non-zero exit code)
        
       - name: Step 4 - I will never execute
         run: |
            echo "I will never execute"

       - name: Step 5- Execute on workflow Failure
         if: ${{failure()}}
         run: |
          echo "Workflow failed"



    