name: Matrix Workflow

on:
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        python-version: ["3.8", "3.9"]
    runs-on: ${{matrix.os}}
    steps:
      - name: Unit_tests
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/set-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install tox
        run: pip install tox

      - name: Run test
        run: |
          cd backend
          tox -e unit
